//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commerce {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label LabelUsername;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.TextBox FirstName;
		
		protected System.Web.UI.WebControls.Label LabelFirstname;
		
		protected System.Web.UI.WebControls.TextBox LastName;
		
		protected System.Web.UI.WebControls.Label LabelLastname;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.Label LabelEmail;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.Label LabelPassword;
		
		protected System.Web.UI.WebControls.TextBox Repeat_Password;
		
		protected System.Web.UI.WebControls.Button Signup;
	}
}
